# Generated by Django 3.2.9 on 2022-01-26 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PDD', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pddimages',
            name='pesticides',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
